version: '3.8'

services:
  backend:
    build: ./backend
    container_name: gan_backend
    ports:
      - "8000:8000"
    # Mapping app so we can edit python code without container rebuild
    volumes:
      - ./backend/app:/code/app
      - ./last_generator.pth:/code/last_generator.pth

  frontend:
    build: ./frontend
    container_name: gan_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
